from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from io import BytesIO

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd


def generate_report(df, insights):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()

    content = []

    # =========================
    # 🏷️ TITLE
    # =========================
    content.append(Paragraph("AI DATA ANALYSIS REPORT", styles["Title"]))
    content.append(Spacer(1, 20))

    # =========================
    # 📊 SUMMARY TABLE
    # =========================
    data = [
        ["Metric", "Value"],
        ["Rows", str(df.shape[0])],
        ["Columns", str(df.shape[1])],
        ["Missing Values", str(int(df.isna().sum().sum()))],
    ]

    table = Table(data)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
    ]))

    content.append(table)
    content.append(Spacer(1, 20))

    # =========================
    # 🚨 ALERTS
    # =========================
    missing_percent = (df.isna().sum().sum() / (df.shape[0] * df.shape[1])) * 100

    if missing_percent > 30:
        content.append(Paragraph("⚠️ High missing data detected", styles["Normal"]))
        content.append(Spacer(1, 10))

    # =========================
    # 📈 HISTOGRAM (FIRST NUMERIC)
    # =========================
    numeric_cols = df.select_dtypes(include='number').columns

    if len(numeric_cols) > 0:
        fig, ax = plt.subplots()
        df[numeric_cols[0]].hist(ax=ax)

        img_buffer = BytesIO()
        plt.savefig(img_buffer, format='png')
        plt.close()

        img_buffer.seek(0)
        content.append(Paragraph(f"Distribution of {numeric_cols[0]}", styles["Heading2"]))
        content.append(Image(img_buffer, width=400, height=250))
        content.append(Spacer(1, 20))

    # =========================
    # 🔥 CORRELATION HEATMAP
    # =========================
    if len(numeric_cols) > 1:
        corr = df[numeric_cols].corr()

        fig, ax = plt.subplots()
        sns.heatmap(corr, annot=True, ax=ax)

        img_buffer = BytesIO()
        plt.savefig(img_buffer, format='png')
        plt.close()

        img_buffer.seek(0)
        content.append(Paragraph("Correlation Heatmap", styles["Heading2"]))
        content.append(Image(img_buffer, width=400, height=300))
        content.append(Spacer(1, 20))

    # =========================
    # 🧠 INSIGHTS
    # =========================
    content.append(Paragraph("AI Insights", styles["Heading2"]))
    content.append(Spacer(1, 10))

    for line in insights.split("\n"):
        if line.strip():
            content.append(Paragraph(line, styles["Normal"]))
            content.append(Spacer(1, 6))

    # =========================
    # 🎯 FOOTER
    # =========================
    content.append(Spacer(1, 20))
    content.append(Paragraph(
        "Generated by AI Data Analyzer — turning data into actionable intelligence.",
        styles["Italic"]
    ))

    doc.build(content)

    buffer.seek(0)
    return buffer